### ISSUE TITLE
HOCR Converter for docx

### ISSUE THREAD

**Issue by manisuresh84** [jbrinley/HocrConverter#3]
Do we have HOCR converter for Docx like PDF?

Thanks,
Suresh Kumar M

**Comment by jbrinley** [comment]
Not here, anyway. Maybe check out another project like https://python-docx.readthedocs.io/en/latest/.

**Comment by manisuresh84** [comment]
thanks Jon! will check on your another project and see, how i can convert HOCR into docx using python-docx.

Thanks again for your time!
